# Custom theme configuration

ostype=$(uname)

# command time & prompt time
DISABLE_ZSH_COMMAND_TIME_MSG=true

AGNOSTERZAK_SHOW_COMMAND_PROMPT_TIME=false
AGNOSTERZAK_SHOW_COMMAND_TIME=true

# git
AGNOSTERZAK_GIT_SHOW_CHANGESET=true
AGNOSTERZAK_GIT_CHANGESET_HASH_LENGTH=6

if [[ $ostype =~ "MSYS_NT" || $ostype =~ "CYGWIN_NT" ]]; then
    AGNOSTERZAK_GIT_SHOW_STASH=false
    AGNOSTERZAK_GIT_SHOW_TAGS=false
    AGNOSTERZAK_GIT_SHOW_UPSTREAM=false
else
    AGNOSTERZAK_GIT_SHOW_STASH=true
    AGNOSTERZAK_GIT_SHOW_TAGS=true
    AGNOSTERZAK_GIT_SHOW_UPSTREAM=true
fi
